
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'Reports'
    ArtifactName: 'Reports'
    publishLocation: 'Container'
- script: |
    npm install -g newman
    mvn clean test
    displayName: 'Run Mobile & API Tests'


