name: Mobile Hybrid Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"   # 02:00 SAST
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: macos-latest

    steps:
      # Checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # Java Setup
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Node + Newman
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Newman
        run: npm install -g newman

      # Install Appium
      - name: Install Appium
        run: |
          npm install -g appium
          appium -v

      - name: Install Appium Drivers
        run: |
          appium driver install uiautomator2
          appium driver install chromium

      # Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Create and start emulator
      - name: Create Emulator
        run: |
          echo "no" | avdmanager create avd -n test-avd -k "system-images;android-30;google_apis;x86_64"
          nohup emulator -avd test-avd -no-snapshot -no-window -noaudio &
          adb wait-for-device
          sleep 25
          adb shell input keyevent 82

      # Start Appium server
      - name: Start Appium Server
        run: |
          nohup appium --allow-insecure chromedriver_autodownload &
          sleep 10

      # Run Maven Tests
      - name: Run Cucumber Tests
        run: mvn clean test -Dcucumber.filter.tags="@mobileWeb"

      # Upload ExtentReport folder
      - name: Upload Extent Report
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReport
          path: Reports/
