name: Mobile Hybrid Automation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"   # 02:00 SAST
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Newman
        run: npm install -g newman

      # Install Appium 3.x
      - name: Install Appium
        run: |
          npm install -g appium@next
          appium -v

      # Install Appium Drivers
      - name: Install Appium Drivers
        run: |
          appium driver install uiautomator2
          appium driver install chromium

      # Install Android SDK and components
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Install Android SDK tools
        run: |
          yes | sdkmanager "platform-tools" "platforms;android-30" "tools" "emulator"

      # Install playable system image (VALID IN 2025)
      - name: Install Android system image
        run: |
          yes | sdkmanager --install "system-images;android-30;google_apis_playstore;x86_64"

      # Create emulator using the installed & valid system image
      - name: Create Emulator
        run: |
          echo "no" | avdmanager create avd \
            -n test-avd \
            -k "system-images;android-30;google_apis_playstore;x86_64" \
            --device "pixel"

      # Boot emulator
      - name: Start Emulator
        run: |
          nohup emulator -avd test-avd -no-snapshot -no-window -noaudio -gpu swiftshader_indirect &
          adb wait-for-device
          sleep 35
          adb shell input keyevent 82

      # Start Appium Server
      - name: Start Appium Server
        run: |
          nohup appium --allow-insecure chromedriver_autodownload &
          sleep 10

      # Run Maven Cucumber Tests
      - name: Run Cucumber Tests
        run: mvn clean test -Dcucumber.filter.tags="@mobileWeb"

      # Upload Extent Report
      - name: Upload Extent Report
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReport
          path: Reports/
